# Generated by Django 2.2.3 on 2021-01-18 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
