# Generated by Django 2.2.3 on 2021-01-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_delete_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(upload_to='', verbose_name='logo of the organization')),
                ('website', models.URLField(verbose_name='website of the organization')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('googlemap_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
