# Generated by Django 2.2.3 on 2020-12-17 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0026_auto_20201217_1404'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='applications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Application', verbose_name='applicationx'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='applicationc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Application', verbose_name='applicationc'),
        ),
    ]
