# Generated by Django 2.2.3 on 2020-12-25 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_historyx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='historyx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.History', verbose_name='history'),
        ),
    ]
