# Generated by Django 2.2.3 on 2020-12-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20201225_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitting',
            name='exam_mark_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Passed', 'Passed'), ('Failed', 'Faild')], default='Pending', max_length=100),
        ),
    ]
