# Generated by Django 2.2.3 on 2020-12-28 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_sitting_exam_mark_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='applicationc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Application', verbose_name='applicationc'),
        ),
    ]
