# Generated by Django 2.2.3 on 2020-12-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20201228_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitting',
            name='exam_mark_status',
        ),
        migrations.AddField(
            model_name='sitting',
            name='interview_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Passed For Interview', 'Passed For Interview'), ('Failed For Interview', 'Failed For Interview')], default='Pending', max_length=100),
        ),
    ]
