# Generated by Django 2.2.3 on 2020-11-03 13:18

from django.db import migrations, models
import django.db.models.deletion
import recruit.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=900, null=True)),
                ('starting_date', models.DateField(auto_now_add=True)),
                ('endingdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typesApps', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoverLetter', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=14, null=True)),
                ('EmailAdd', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Mname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNo', models.CharField(max_length=13)),
                ('Nationality', models.CharField(max_length=50)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('DateofBirth', models.DateField()),
                ('PlaceofBirth', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=14, null=True)),
                ('EmailAdd', models.EmailField(blank=True, max_length=254, null=True)),
                ('CoverLetter', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='', validators=[recruit.validators.validate_file_extension])),
                ('categories', models.ManyToManyField(to='recruit.Interest')),
                ('userx', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=50)),
                ('Writing', models.CharField(choices=[('excellent', 'Excellent'), ('verygood', 'Very Good'), ('good', 'Good'), ('poor', 'Poor')], max_length=10)),
                ('Listening', models.CharField(choices=[('excellent', 'Excellent'), ('verygood', 'Very Good'), ('good', 'Good'), ('poor', 'Poor')], max_length=10)),
                ('Speaking', models.CharField(choices=[('excellent', 'Excellent'), ('verygood', 'Very Good'), ('good', 'Good'), ('poor', 'Poor')], max_length=10)),
                ('Reading', models.CharField(choices=[('excellent', 'Excellent'), ('verygood', 'Very Good'), ('good', 'Good'), ('poor', 'Poor')], max_length=10)),
                ('languageskills', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personallangu', to='recruit.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=800, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Application')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruit.Status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(blank=True, max_length=200, null=True)),
                ('Position', models.CharField(blank=True, max_length=200, null=True)),
                ('YearofExp', models.CharField(blank=True, choices=[('0-2', '0-2 Years'), ('3-4', '3-4 Years'), ('5-9', '5-9 Years'), ('10+', '10+ Years')], max_length=10, null=True)),
                ('Start', models.DateField(blank=True, null=True)),
                ('End', models.DateField(blank=True, null=True)),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personalexxp', to='recruit.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Edubackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('University', models.CharField(max_length=200)),
                ('FieldofStudy', models.CharField(max_length=200)),
                ('Degree_level', models.CharField(choices=[('bsc', 'BSc'), ('msc', 'Msc'), ('phd', 'Phd')], max_length=10)),
                ('From', models.DateField()),
                ('To', models.DateField()),
                ('edubackground', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personaledu', to='recruit.PersonalInfo')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruit.ApplicationType'),
        ),
    ]
