# Generated by Django 2.2.3 on 2020-11-12 11:11

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_auto_20201112_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='PhoneNo',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='EH'),
        ),
    ]
