# Generated by Django 2.2.3 on 2020-11-12 11:14

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_auto_20201112_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='PhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='ET'),
        ),
    ]
