# Generated by Django 2.2.3 on 2020-11-12 11:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0005_auto_20201112_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='PhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='ET'),
        ),
    ]
