# Generated by Django 2.2.3 on 2020-11-23 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('recruit', '0007_auto_20201123_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='categories',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='categories',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Category'),
        ),
    ]
