# Generated by Django 2.2.3 on 2020-11-24 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0008_auto_20201123_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Category'),
        ),
    ]
