# Generated by Django 2.2.3 on 2020-12-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0010_auto_20201201_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='postion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='qualifaction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='required_experinace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='edubackground',
            name='cumulative_gpa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='disablity',
            field=models.BooleanField(default=False, verbose_name='True if the pearson is disabled '),
        ),
        migrations.AlterField(
            model_name='application',
            name='starting_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='edubackground',
            name='Degree_level',
            field=models.CharField(choices=[('bachelor', 'Bachelor'), ('masters ', 'Masters '), ('doctor of philosophy', 'Doctor of Philosophy')], max_length=10),
        ),
    ]
