# Generated by Django 2.2.3 on 2020-12-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0011_auto_20201208_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elementary_School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_name', models.CharField(max_length=200)),
                ('starting_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Preparatory_School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_namep', models.CharField(max_length=200)),
                ('starting_datep', models.DateField()),
                ('end_datesp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Secondary_School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_names', models.CharField(max_length=200)),
                ('starting_dates', models.DateField()),
                ('end_dates', models.DateField()),
            ],
        ),
    ]
