# Generated by Django 2.2.3 on 2020-12-10 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0012_elementary_school_preparatory_school_secondary_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementary_school',
            name='pinfoe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_elementary', to='recruit.PersonalInfo'),
        ),
        migrations.AddField(
            model_name='preparatory_school',
            name='pinfop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_preparatory', to='recruit.PersonalInfo'),
        ),
        migrations.AddField(
            model_name='secondary_school',
            name='pinfos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_Secondary', to='recruit.PersonalInfo'),
        ),
    ]
