# Generated by Django 2.2.3 on 2020-12-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0015_auto_20201212_1640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commitee',
        ),
    ]
