# Generated by Django 2.2.3 on 2020-12-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0017_auto_20201215_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Applicaton Initiated', 'Applicaton Initiated'), ('READY for EXAM', 'READY for EXAM'), ('DECLINED FOR EXAM', 'DECLINED FOR EXAM'), ('E-passed', 'Passed for Exam'), ('E-failed', 'Failed for Exam'), ('I-SCHEDULED', 'INTERVIEW SCHEDULED'), ('INTERVIEW PASSED', 'INTERVIEW PASSED'), ('INTERVIEW FAILED', 'INTERVIEW FAILED')], default='pending', max_length=100),
        ),
    ]
