# Generated by Django 2.2.3 on 2020-12-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0018_auto_20201215_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal', to='recruit.PersonalInfo'),
        ),
    ]
