# Generated by Django 2.2.3 on 2020-12-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0019_history_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Applicaton Initiated', 'Applicaton Initiated'), ('READY for EXAM', 'READY for EXAM'), ('DECLINED FOR EXAM', 'DECLINED FOR EXAM'), ('Passed for Exam', 'Passed for Exam'), ('Failed for Exam', 'Failed for Exam'), ('INTERVIEW SCHEDULED', 'INTERVIEW SCHEDULED'), ('INTERVIEW PASSED', 'INTERVIEW PASSED'), ('INTERVIEW FAILED', 'INTERVIEW FAILED')], default='pending', max_length=100),
        ),
    ]
