# Generated by Django 2.2.3 on 2020-12-17 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0020_auto_20201216_0719'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='experience',
            unique_together={('Start', 'End')},
        ),
    ]
