# Generated by Django 2.2.3 on 2020-12-17 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0021_auto_20201217_0541'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='experience',
            unique_together=set(),
        ),
    ]
