# Generated by Django 2.2.3 on 2020-12-17 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0022_auto_20201217_0542'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='experience',
            unique_together={('Start', 'End')},
        ),
    ]
