# Generated by Django 2.2.3 on 2020-12-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0025_auto_20201217_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='exam_result',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Passed', 'Passed'), ('Failed', 'Faild')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='history',
            name='exam_status',
            field=models.CharField(choices=[('Dectivate', 'Dectivate'), ('Active', 'Active'), ('Closed', 'Closed')], default='Dectivate', max_length=100),
        ),
    ]
