# Generated by Django 2.2.3 on 2020-12-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0026_auto_20201217_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='YearofExp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
