# Generated by Django 2.2.3 on 2020-12-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0029_auto_20201221_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edubackground',
            name='Degree_level',
            field=models.CharField(choices=[('bachelor', 'Bachelor'), ('masters ', 'Masters '), ('doctor of philosophy', 'Doctor of Philosophy')], max_length=40),
        ),
        migrations.AlterField(
            model_name='edubackground',
            name='cumulative_gpa',
            field=models.CharField(max_length=60),
        ),
    ]
