# Generated by Django 2.2.3 on 2020-12-25 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20201225_1540'),
        ('recruit', '0031_auto_20201225_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='exam_result',
            new_name='exam_marks',
        ),
        migrations.AddField(
            model_name='history',
            name='exam_resultx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultx', to='quiz.Sitting'),
        ),
    ]
