# Generated by Django 2.2.3 on 2020-12-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0032_auto_20201225_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='exam_marks',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Passed For Interview', 'Passed For Interview'), ('Failed For Interview', 'Failed For Interview')], default='Pending', max_length=100),
        ),
    ]
