# Generated by Django 2.2.3 on 2021-01-05 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0034_auto_20210105_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Interivew_date_notfied',
            field=models.BooleanField(default=False, verbose_name='if the applicant has been notfied for interview date  '),
        ),
        migrations.AddField(
            model_name='history',
            name='exam_date_notfied',
            field=models.BooleanField(default=False, verbose_name='if the applicant has been notfied for exam date  '),
        ),
        migrations.CreateModel(
            name='Interview_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_message', models.CharField(max_length=10020)),
                ('interview_date', models.DateField(verbose_name='Interview Scheduling Date')),
                ('interview_time', models.TimeField()),
                ('time_set', models.CharField(choices=[('A.M', 'A.M'), ('P.M', 'P.M')], default='A.M', max_length=10)),
                ('interview_location', models.CharField(max_length=500)),
                ('google_map_link', models.URLField(blank=True, null=True)),
                ('application_userx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruit.Application')),
                ('history_userx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruit.History')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_message', models.CharField(blank=True, max_length=10020, null=True)),
                ('exam_date', models.DateField(verbose_name='the date when the exam is held ')),
                ('exam_time', models.TimeField()),
                ('time_set', models.CharField(choices=[('A.M', 'A.M'), ('P.M', 'P.M')], default='A.M', max_length=10)),
                ('exam_location', models.CharField(max_length=500)),
                ('google_map_link', models.URLField(blank=True, null=True)),
                ('application_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruit.Application')),
                ('history_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruit.History')),
            ],
        ),
    ]
