# Generated by Django 2.2.3 on 2021-01-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0035_auto_20210105_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='Interivew_date_notfied',
        ),
        migrations.RemoveField(
            model_name='history',
            name='exam_date_notfied',
        ),
        migrations.AddField(
            model_name='history',
            name='Interivew_date_notified',
            field=models.BooleanField(default=False, verbose_name='if the applicant has been notified for interview date  '),
        ),
        migrations.AddField(
            model_name='history',
            name='exam_date_notified',
            field=models.BooleanField(default=False, verbose_name='if the applicant has been notified for exam date  '),
        ),
        migrations.AddField(
            model_name='history',
            name='failed_exam_notified',
            field=models.BooleanField(default=False, verbose_name='if the applicant has been notified if failed for exam  '),
        ),
        migrations.AddField(
            model_name='history',
            name='failed_interview_notified',
            field=models.BooleanField(default=False, verbose_name='if the applicant has been notified if failed for interview  '),
        ),
        migrations.AddField(
            model_name='history',
            name='failed_screning_notified',
            field=models.BooleanField(default=False, verbose_name='if the applicant has been notified if failed for screning  '),
        ),
    ]
