# Generated by Django 2.2.3 on 2021-01-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0036_auto_20210105_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_schedule',
            name='time_set',
        ),
    ]
