# Generated by Django 2.2.3 on 2021-01-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0037_remove_exam_schedule_time_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_schedule',
            name='history_user',
        ),
    ]
