# Generated by Django 2.2.3 on 2021-01-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0038_remove_exam_schedule_history_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_exam', models.CharField(blank=True, max_length=10020, null=True)),
                ('message_interview', models.CharField(blank=True, max_length=10020, null=True)),
            ],
        ),
    ]
