# Generated by Django 2.2.3 on 2021-01-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0040_auto_20210105_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Interivew_date_notifiedyx',
            field=models.BooleanField(default=False, verbose_name='if the applicant has been notified for interview date  '),
        ),
        migrations.AddField(
            model_name='application',
            name='exam_date_notifiedyx',
            field=models.BooleanField(default=False, verbose_name='if the applicant has been notified for exam date  '),
        ),
        migrations.AddField(
            model_name='application',
            name='failed_exam_notifiedyx',
            field=models.BooleanField(default=False, verbose_name='if the applicant has been notified if failed for exam  '),
        ),
        migrations.AddField(
            model_name='application',
            name='failed_interview_notifiedyx',
            field=models.BooleanField(default=False, verbose_name='if the applicant has been notified if failed for interview  '),
        ),
        migrations.AddField(
            model_name='application',
            name='failed_screning_notifiedyx',
            field=models.BooleanField(default=False, verbose_name='if the applicant has been notified if failed for screning  '),
        ),
    ]
