# Generated by Django 2.2.3 on 2021-01-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0041_auto_20210105_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='Interivew_date_notified',
            new_name='Interivew_date_notified_email',
        ),
        migrations.AddField(
            model_name='history',
            name='failed_exam_notified_email',
            field=models.BooleanField(default=False, verbose_name='if the applicant has been notified if failed for exam  '),
        ),
        migrations.AddField(
            model_name='history',
            name='failed_interview_notified_email',
            field=models.BooleanField(default=False, verbose_name='if the applicant has been notified if failed for interview  '),
        ),
        migrations.AddField(
            model_name='history',
            name='failed_screning_notified_email',
            field=models.BooleanField(default=False, verbose_name='if the applicant has been notified if failed for screning  '),
        ),
    ]
