# Generated by Django 2.2.3 on 2021-01-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0042_auto_20210114_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='Interivew_date_notified_email',
            field=models.BooleanField(default=False, verbose_name='if the applicant has been notified for interview date via email  '),
        ),
        migrations.AlterField(
            model_name='history',
            name='failed_exam_notified_email',
            field=models.BooleanField(default=False, verbose_name='if the applicant has been notified if failed for exam  via email  '),
        ),
        migrations.AlterField(
            model_name='history',
            name='failed_interview_notified_email',
            field=models.BooleanField(default=False, verbose_name='if the applicant has been notified if failed for interview via email  '),
        ),
        migrations.AlterField(
            model_name='history',
            name='failed_screning_notified_email',
            field=models.BooleanField(default=False, verbose_name='if the applicant has been notified if failed for screning via email  '),
        ),
    ]
