# Generated by Django 2.2.3 on 2021-01-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0043_auto_20210114_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Interivew_date_notified',
            field=models.BooleanField(default=False, verbose_name='if the applicant has been notified for interview date   '),
        ),
        migrations.AddField(
            model_name='history',
            name='exam_date_notified_email',
            field=models.BooleanField(default=False, verbose_name='if the applicant has been notified for exam date via email  '),
        ),
    ]
