# Generated by Django 2.2.3 on 2021-01-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0044_auto_20210115_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
