# Generated by Django 2.2.3 on 2021-01-17 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0046_auto_20210117_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview_Schedule_User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('application_f', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.Application')),
                ('history_userx_f', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruit.History', verbose_name='Interview Schedule Per User')),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
