# Generated by Django 2.2.3 on 2021-01-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0047_auto_20210117_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview_schedule_user',
            name='google_map_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview_schedule_user',
            name='interview_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
