# Generated by Django 2.2.3 on 2021-01-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0048_auto_20210117_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interview_Schedule_User',
        ),
    ]
