# Generated by Django 2.2.3 on 2021-01-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0050_auto_20210117_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interview_Schedule',
        ),
    ]
