# Generated by Django 2.2.3 on 2021-01-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0053_auto_20210118_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='interview_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='interview_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
