# Generated by Django 2.2.3 on 2021-01-25 00:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0054_auto_20210119_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='detail',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
